// List of available themes from textmate-grammars-themes

const BASE_PATH = `${import.meta.env.BASE_URL}tm-themes`;

export async function getAvailableThemes() {
    return [
        {
            name: 'dark-plus',
            displayName: 'Dark+ (default dark)',
            path: `${BASE_PATH}/dark-plus.json`,
            type: 'dark',
        },
        {
            name: 'light-plus',
            displayName: 'Light+ (default light)',
            path: `${BASE_PATH}/light-plus.json`,
            type: 'light',
        },
        {
            name: 'monokai',
            displayName: 'Monokai',
            path: `${BASE_PATH}/monokai.json`,
            type: 'dark',
        },
        {
            name: 'github-dark',
            displayName: 'GitHub Dark',
            path: `${BASE_PATH}/github-dark-default.json`,
            type: 'dark',
        },
        {
            name: 'github-light',
            displayName: 'GitHub Light',
            path: `${BASE_PATH}/github-light-default.json`,
            type: 'light',
        },
        {
            name: 'dracula',
            displayName: 'Dracula',
            path: `${BASE_PATH}/dracula.json`,
            type: 'dark',
        },
        {
            name: 'one-dark-pro',
            displayName: 'One Dark Pro',
            path: `${BASE_PATH}/one-dark-pro.json`,
            type: 'dark',
        },
        {
            name: 'nord',
            displayName: 'Nord',
            path: `${BASE_PATH}/nord.json`,
            type: 'dark',
        },
        {
            name: 'tokyo-night',
            displayName: 'Tokyo Night',
            path: `${BASE_PATH}/tokyo-night.json`,
            type: 'dark',
        },
        {
            name: 'night-owl',
            displayName: 'Night Owl',
            path: `${BASE_PATH}/night-owl.json`,
            type: 'dark',
        },
        {
            name: 'material-theme',
            displayName: 'Material Theme',
            path: `${BASE_PATH}/material-theme.json`,
            type: 'dark',
        },
        {
            name: 'material-theme-ocean',
            displayName: 'Material Theme Ocean',
            path: `${BASE_PATH}/material-theme-ocean.json`,
            type: 'dark',
        },
        {
            name: 'material-theme-darker',
            displayName: 'Material Theme Darker',
            path: `${BASE_PATH}/material-theme-darker.json`,
            type: 'dark',
        },
        {
            name: 'material-theme-palenight',
            displayName: 'Material Theme Palenight',
            path: `${BASE_PATH}/material-theme-palenight.json`,
            type: 'dark',
        },
        {
            name: 'solarized-dark',
            displayName: 'Solarized Dark',
            path: `${BASE_PATH}/solarized-dark.json`,
            type: 'dark',
        },
        {
            name: 'solarized-light',
            displayName: 'Solarized Light',
            path: `${BASE_PATH}/solarized-light.json`,
            type: 'light',
        },
        {
            name: 'gruvbox-dark-hard',
            displayName: 'Gruvbox Dark Hard',
            path: `${BASE_PATH}/gruvbox-dark-hard.json`,
            type: 'dark',
        },
        {
            name: 'gruvbox-dark-medium',
            displayName: 'Gruvbox Dark Medium',
            path: `${BASE_PATH}/gruvbox-dark-medium.json`,
            type: 'dark',
        },
        {
            name: 'gruvbox-dark-soft',
            displayName: 'Gruvbox Dark Soft',
            path: `${BASE_PATH}/gruvbox-dark-soft.json`,
            type: 'dark',
        },
        {
            name: 'gruvbox-light-hard',
            displayName: 'Gruvbox Light Hard',
            path: `${BASE_PATH}/gruvbox-light-hard.json`,
            type: 'light',
        },
        {
            name: 'gruvbox-light-medium',
            displayName: 'Gruvbox Light Medium',
            path: `${BASE_PATH}/gruvbox-light-medium.json`,
            type: 'light',
        },
        {
            name: 'gruvbox-light-soft',
            displayName: 'Gruvbox Light Soft',
            path: `${BASE_PATH}/gruvbox-light-soft.json`,
            type: 'light',
        },
        {
            name: 'catppuccin-frappe',
            displayName: 'Catppuccin Frappé',
            path: `${BASE_PATH}/catppuccin-frappe.json`,
            type: 'dark',
        },
        {
            name: 'catppuccin-latte',
            displayName: 'Catppuccin Latte',
            path: `${BASE_PATH}/catppuccin-latte.json`,
            type: 'light',
        },
        {
            name: 'catppuccin-macchiato',
            displayName: 'Catppuccin Macchiato',
            path: `${BASE_PATH}/catppuccin-macchiato.json`,
            type: 'dark',
        },
        {
            name: 'catppuccin-mocha',
            displayName: 'Catppuccin Mocha',
            path: `${BASE_PATH}/catppuccin-mocha.json`,
            type: 'dark',
        },
        {
            name: 'vitesse-dark',
            displayName: 'Vitesse Dark',
            path: `${BASE_PATH}/vitesse-dark.json`,
            type: 'dark',
        },
        {
            name: 'vitesse-light',
            displayName: 'Vitesse Light',
            path: `${BASE_PATH}/vitesse-light.json`,
            type: 'light',
        },
        {
            name: 'vitesse-black',
            displayName: 'Vitesse Black',
            path: `${BASE_PATH}/vitesse-black.json`,
            type: 'dark',
        },
        {
            name: 'ayu-dark',
            displayName: 'Ayu Dark',
            path: `${BASE_PATH}/ayu-dark.json`,
            type: 'dark',
        },
        {
            name: 'ayu-light',
            displayName: 'Ayu Light',
            path: `${BASE_PATH}/ayu-light.json`,
            type: 'light',
        },
        {
            name: 'everforest-dark',
            displayName: 'Everforest Dark',
            path: `${BASE_PATH}/everforest-dark.json`,
            type: 'dark',
        },
        {
            name: 'everforest-light',
            displayName: 'Everforest Light',
            path: `${BASE_PATH}/everforest-light.json`,
            type: 'light',
        },
        {
            name: 'min-dark',
            displayName: 'Min Dark',
            path: `${BASE_PATH}/min-dark.json`,
            type: 'dark',
        },
        {
            name: 'min-light',
            displayName: 'Min Light',
            path: `${BASE_PATH}/min-light.json`,
            type: 'light',
        },
        {
            name: 'laserwave',
            displayName: 'LaserWave',
            path: `${BASE_PATH}/laserwave.json`,
            type: 'dark',
        },
        {
            name: 'vesper',
            displayName: 'Vesper',
            path: `${BASE_PATH}/vesper.json`,
            type: 'dark',
        },
        {
            name: 'aurora-x',
            displayName: 'Aurora X',
            path: `${BASE_PATH}/aurora-x.json`,
            type: 'dark',
        },
        {
            name: 'red',
            displayName: 'Red',
            path: `${BASE_PATH}/red.json`,
            type: 'dark',
        },
        {
            name: 'slack-dark',
            displayName: 'Slack Dark',
            path: `${BASE_PATH}/slack-dark.json`,
            type: 'dark',
        },
        {
            name: 'slack-ochin',
            displayName: 'Slack Ochin',
            path: `${BASE_PATH}/slack-ochin.json`,
            type: 'light',
        },
        {
            name: 'snazzy-light',
            displayName: 'Snazzy Light',
            path: `${BASE_PATH}/snazzy-light.json`,
            type: 'light',
        },
    ];
}
