#!/bin/bash
set -e

# Example changeset markdown format (both single and double quotes supported):
# ---
# 'textmatelib': minor
# ---
#
# Added support for incremental tokenization with line caching

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# Parse changesets and determine bump type
BUMP_TYPE="patch"
CHANGELOG=""

for file in "$ROOT_DIR"/.changeset/*.md; do
    [ -f "$file" ] || continue

    # Skip README.md
    [ "$(basename "$file")" = "README.md" ] && continue

    # Extract bump type from frontmatter
    type=$(sed -n '/^---$/,/^---$/p' "$file" | grep -E "^\s*[\"']?textmatelib[\"']?\s*:" | sed 's/.*:\s*//' | tr -d " \"'")

    case "$type" in
        major) BUMP_TYPE="major" ;;
        minor) [ "$BUMP_TYPE" != "major" ] && BUMP_TYPE="minor" ;;
    esac

    # Extract description (after second ---)
    desc=$(sed '1,/^---$/d;1,/^---$/d' "$file" | sed '/^$/d')
    CHANGELOG="$CHANGELOG\n- $desc"
done

# Get current version from package.json
CURRENT_VERSION=$(grep '"version"' "$ROOT_DIR/src/js/package.json" | head -1 | sed 's/.*"\([0-9.]*\)".*/\1/')
IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

# Calculate new version
case "$BUMP_TYPE" in
    major) NEW_VERSION="$((MAJOR + 1)).0.0" ;;
    minor) NEW_VERSION="$MAJOR.$((MINOR + 1)).0" ;;
    patch) NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))" ;;
esac

echo "Bumping version: $CURRENT_VERSION -> $NEW_VERSION ($BUMP_TYPE)"

# Update CMakeLists.txt
sed -i.bak "s/project(tml VERSION [0-9.]*/project(tml VERSION $NEW_VERSION/" "$ROOT_DIR/CMakeLists.txt"
rm -f "$ROOT_DIR/CMakeLists.txt.bak"

# Update conanfile.py
sed -i.bak "s/version = \"[0-9.]*\"/version = \"$NEW_VERSION\"/" "$ROOT_DIR/conanfile.py"
rm -f "$ROOT_DIR/conanfile.py.bak"

# Update src/js/package.json
cd "$ROOT_DIR/src/js" && npm pkg set version="$NEW_VERSION"

# Update NuGet csproj
sed -i.bak "s/<Version>[0-9.]*<\/Version>/<Version>$NEW_VERSION<\/Version>/" \
    "$ROOT_DIR/src/csharp/TextMateLib.Bindings/TextMateLib.Bindings.csproj"
rm -f "$ROOT_DIR/src/csharp/TextMateLib.Bindings/TextMateLib.Bindings.csproj.bak"

# Update playground/package.json
cd "$ROOT_DIR/playground" && npm pkg set version="$NEW_VERSION"

# Delete consumed changesets (keep README.md)
for file in "$ROOT_DIR"/.changeset/*.md; do
    [ "$(basename "$file")" != "README.md" ] && rm -f "$file"
done

# Generate PR body
cat > /tmp/pr-body.md << EOF
## Version $NEW_VERSION

This PR was automatically generated by the changeset workflow.

### Changes
$(echo -e "$CHANGELOG")

### Updated Files
- CMakeLists.txt
- conanfile.py
- src/js/package.json
- src/csharp/TextMateLib.Bindings/TextMateLib.Bindings.csproj
- playground/package.json
EOF

[ -n "$GITHUB_OUTPUT" ] && echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
